<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2 class="text-center"><?= $editing ? 'Editar Pelicula' : 'Nueva Pelicula' ?></h2>
            <form action="<?= $editing ? BASE_URL . 'updatePlatform/' . $platform->id_plataforma : BASE_URL . 'addPlatform' ?>" method="POST">
                <div class="form-group">
                    <label for="nombre">Nombre</label>
                    <input type="text" class="form-control" name="nombre" value="<?= $editing ? $platform->nombre : '' ?>">
                </div>
                <div class="form-group">
                    <label for="enlace">Enlace:</label>
                    <input type="text" class="form-control" name="enlace" value="<?= $editing ? $platform->enlace : '' ?>">
                </div>
                <button type="submit" class="btn btn-primary"><?= $editing ? 'Editar' : 'Enviar' ?></button>
            </form>
        </div>
    </div>
</div>