<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2 class="text-center"><?= $editing ? 'Editar Plataforma' : 'Nueva Plataforma' ?></h2>
            <form action="<?= $editing ? BASE_URL . 'updatePlataforma/' . $platform->id_plataforma : BASE_URL . 'addPlatform' ?>" method="POST">
                <div class="form-group">
                    <label for="nombre">Nombre</label>
                    <input type="text" class="form-control" name="nombre" value="<?= $editing ? $platform->nombre : '' ?>">
                </div>
                <div class="form-group">
                    <label for="enlace">Enlace:</label>
                    <input type="text" class="form-control" name="enlace" value="<?= $editing ? $platform->enlace : '' ?>">
                </div>
                <div class="form-group">
                    <label for="tipo_contenido">tipo_contenido:</label>
                    <input type="text" class="form-control" name="tipo_contenido" value="<?= $editing ? $platform->tipo_contenido : '' ?>">
                </div>
                <div class="form-group">
                    <label for="disponibilidad_ar">disponibilidad_ar:</label>
                    <input type="checkbox" value = "1" class="form-control" name="disponibilidad_ar" value="<?= $editing ? $platform->disponibilidad_ar : '' ?>">
                </div>
                <div class="form-group">
                    <label for="precio">precio:</label>
                    <input type="number" class="form-control" name="precio" value="<?= $editing ? $platform->precio : '' ?>">
                </div>

                <div class="form-group">
                    <label for="link_logo">Enlace del logo</label>
                    <input type="text" class="form-control" name="link_logo" value="<?= $editing ? $platform->link_logo : '' ?>">
                </div>

                <button type="submit" class="btn btn-primary"><?= $editing ? 'Editar' : 'Enviar' ?></button>
            </form>
        </div>
    </div>
</div>


<!-- Si la funcion se llama sin parametros, editing es false, por lo tanto, no se precargan datos
Si la funcion se llama con editing = true y la plataforma correspondiente, se precargan los datos
del formulario segun los de la plataforma -->