<?php session_start(); ?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StreamingNet</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="<?=BASE_URL?>">StreamingNet</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="<?=BASE_URL?>home">Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="<?=BASE_URL?>peliculas">Peliculas</a>
                <a class="nav-item nav-link" href="<?=BASE_URL?>plataformas">Plataformas</a>
                <a class="nav-item nav-link" href="#">About</a> <!-- Pendiente -->
            </div>

            <div class="ml-auto">
                <!-- Condicion, si el usuario no inicio sesion "iniciar sesion" y si lo hizo "cerrar sesion" -->
                <?php if (isset($_SESSION["id"])): ?>
                    <a class="nav-item nav-link btn btn-danger rounded" href="<?=BASE_URL?>logout">Cerrar Sesión</a>
                <?php else: ?>
                    <a class="nav-item nav-link btn btn-success rounded" href="<?=BASE_URL?>auth">Iniciar Sesión</a>
                <?php endif ?>
            </div>
            </div>
        </nav>
    </header>

    <?php if (isset($titulo) && isset($subtitulo)):?>

        <h1 class="text-center">
            <?= $titulo ?>
        </h1>
        <h2 class="text-center">
            <?= $subtitulo ?>
        </h2>

        <hr>

    <?php endif?>
</body>

</html>