<div class="list-group col-md-6 mx-auto">
<a href="#" class="list-group-item list-group-item-action active">Peliculas</a>
<?php foreach ($movies as $movie):?>
        <div class="d-flex justify-content-between align-items-center">
                <a href="<?=BASE_URL?>peliculas/<?=$movie->id_pelicula?>" class="list-group-item list-group-item-action"><?=$movie->titulo?></a>
                <button class="btn btn-warning">Editar</button>
                <button class="btn btn-danger">Eliminar</button>
        </div>
       <?php endforeach?> 
</div>

<div class="text-center">
        <a href="<?=BASE_URL?>agregarPelicula"><button type="button" class="btn btn-outline-primary mx-auto">Agregar nueva pelicula</button></a>
</div>
