<link rel="stylesheet" href="<?=BASE_URL?>css/articleDetail.css">
<div class="container">
    <h1 class="mt-5">Detalles de la Película</h1>
    <div class="row mt-4">
        <div class="col-md-6">
       
            <img src="<?=$details->link_portada?>" alt="Imagen de la Película" class="img-fluid articleImage">
        </div>
        <div class="col-md-6">
        
            <h2><?=$details->titulo?></h2>
            <p><strong>Sinopsis:</strong> <?=$details->sinopsis?></p>
            <p><strong>Director:</strong> <?=$details->director?></p>
            <p><strong>Fecha de Lanzamiento:</strong> <?=$details->año_lanzamiento?></p>
            <p><strong>Cast:</strong> <?=$details->cast?></p>
            <p><strong>Plataforma:</strong> <a href="<?=BASE_URL?>plataforma/<?=$details->plataforma_id?>" class="list-group-item list-group-item-action"><?=$details->nombre?></a></p>
        </div>
    </div>
</div>