<link rel="stylesheet" href="<?=BASE_URL?>css/articleDetail.css">
<div class="container">
    <div class="row mt-4">
        <div class="col-md-6">
            <!-- Agrega una imagen de la plataforma -->
            <img src="<?=$details->link_logo?>" alt="Imagen de la Plataforma" class="img-fluid articleImage">
        </div>
        <div class="col-md-6">
            <!-- Agrega los detalles de la plataforma -->
            <a href="<?=$details->enlace?>" class="text-decoration-none"><h2><?=$details->nombre?></h2></a>
            <?php if ($details->disponibilidad_ar == 1):?>
                <p><strong>Disponible en tu region</strong></p>
            <?php else:?>
                <p><strong>No disponible en tu region</strong></p>
            <?php endif?>
            <p><strong>Tipo de Contenido:</strong> <?=$details->tipo_contenido?></p>
            <p><strong>Precio: $</strong> <?=$details->precio?></p>
            <h1>CATÁLOGO DISPONIBLE:</h1>
            
            <!-- Muestra todas las peliculas de esta plataforma -->
        <div class="row row-cols-2 row-cols-md-4 g-4">
            <?php foreach ($movies as $movie): ?>
                <div class="col">
                    <a href="<?=BASE_URL?>peliculas/<?=$movie->id_pelicula?>" class="text-decoration-none">
                        <img src="<?= $movie->link_portada ?>" alt="Imagen de la Película" class="img-fluid movieDetails-image">
                        <p class="text-decoration-none"><?= $movie->titulo ?></p>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>


