<div class="container">
    <h1 class="mt-5">Detalles de la Plataforma</h1>
    <div class="row mt-4">
        <div class="col-md-6">
            <!-- Agrega una imagen de la plataforma -->
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Placeholder_view_vector.svg/310px-Placeholder_view_vector.svg.png" alt="Imagen de la Plataforma" class="img-fluid">
        </div>
        <div class="col-md-6">
            <!-- Agrega los detalles de la plataforma -->
            <h2><?=$details->nombre?></h2>
            <p><strong>Acceso directo:</strong> <?=$details->enlace?></p>
            <p><strong>Tipo de Contenido:</strong> <?=$details->tipo_contenido?></p>
            <p><strong>Disponibilidad:</strong> <?=$details->disponibilidad_ar?></p>
            <p><strong>Precio: $</strong> <?=$details->precio?></p>
            <h1>CATÁLOGO DISPONIBLE:</h1>
            
            <!-- Agrega un bucle para mostrar las películas -->
            <?php foreach ($movies as $movie): ?>
                <div class="movie-details">
                    <a href="<?=BASE_URL?>peliculas/<?=$movie->id_pelicula?>" class="list-group-item list-group-item-action"><?=$movie->titulo?></a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>