<div class="container mt-4">
<div class="row">
        <?php foreach ($platforms as $platform):?>
        <div class="col-md-4 mb-3">
        <div class="card">
        <div class="card-body d-flex justify-content-between align-items-center">
        <h5 class="card-title">
                <a href="<?=BASE_URL?>plataforma/<?=$platform->id_plataforma?>" class="font-weight-bold text-dark text-decoration-none"><?=$platform->nombre?></a>
        </h5>
        <?php if (isset($_SESSION["id"])):?>
        <div class="btn-group" role="group">
                <a href="<?=BASE_URL?>editarPlataforma/<?=$platform->id_plataforma?>" class="btn btn-warning btn-sm">Editar</a>
                <a href="<?=BASE_URL?>eliminarPlataforma/<?=$platform->id_plataforma?>" class="btn btn-danger btn-sm">Eliminar</a>
        </div>
        <?php endif?>
        </div>
        </div>
        </div>
        <?php endforeach?>
</div>

<?php if (isset($_SESSION["id"])):?>
<div class="text-center">
        <a href="<?=BASE_URL?>agregarPlataforma" class="btn btn-outline-primary">Agregar servicio de Streaming</a>
</div>
<?php endif?>
</div>

<!-- Los botones de edicion solo se muestran si el usuario esta logueado (Si existe una id del $_SESSION) -->